### ISSUE TITLE
@import section when combining css files

### ISSUE THREAD

**Issue by milsorm** [JanGalek/CombineFiles#2]
@import section needs to be put in front of file

Do you thing about building bridge in Compiler to some existing combinator + minificator? Because use inside config.neon and @layout is quite handy but functionallity is very poor now.

**Comment by JanGalek** [comment]
I look at it, weekend.

**Comment by JanGalek** [comment]
@milsorm I thing about minificator, and I'll try something. **Bridge** for Nette was added ;)
